firstName = input("Cual es tu nombre? ")
lastName = input("Cual es tu apellido? ")
codesec = input("Cual es tu seccion? ")
sede = input("Cual es tu sede? ")
print("Hola " + firstName, lastName + "! Tu ubicación es "+ codesec +" y tienes "+sede +" años.")